//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Db.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockInTrade
    {
        public long StockInTradeId { get; set; }
        public string StockSerial { get; set; }
        public int InitialQuantity { get; set; }
        public Nullable<int> QuantityLeft { get; set; }
        public long UnitId { get; set; }
        public Nullable<float> PricePerUnit { get; set; }
        public long CurrencyId { get; set; }
        public long ProductId { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Product Product { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
